# TODO: 需修改的配置，用于上传到 CloudFlare
name = "friendlink"
type = "webpack"
account_id = "714b60da0281842b74b67f4a5bfb66db"
workers_dev = true
# route = "blogroll.icl.moe/*"
zone_id = "374cfa163417e4f4a64edb66a0ddc218"

[site]
bucket = "./web/dist"
entry-point = "workers-site"
